/**
 ******************************************************************************
 * @file           : main.cpp
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <cstdint>
#include <cstdio>
#include "stm32f4xx_hal.h"

#include "FreeRTOS.h"
#include "task.h"

#include "hts221_task.h"

I2C_HandleTypeDef hi2c1;
UART_HandleTypeDef huart2;

extern "C" int __io_putchar(int ch) {
    uint8_t c = static_cast<uint8_t>(ch);
    HAL_UART_Transmit(&huart2, &c, 1, HAL_MAX_DELAY);
    return ch;
}

static void MX_GPIO_Init(void) {
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};
    gpio.Pin = GPIO_PIN_8 | GPIO_PIN_9; 
    gpio.Mode = GPIO_MODE_AF_OD;
    gpio.Pull = GPIO_PULLUP;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    gpio.Alternate = GPIO_AF4_I2C1;
    HAL_GPIO_Init(GPIOB, &gpio);

    GPIO_InitTypeDef uart_gpio = {0};
    uart_gpio.Pin = GPIO_PIN_2 | GPIO_PIN_3; 
    uart_gpio.Mode = GPIO_MODE_AF_PP;
    uart_gpio.Pull = GPIO_NOPULL;
    uart_gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    uart_gpio.Alternate = GPIO_AF7_USART2;
    HAL_GPIO_Init(GPIOA, &uart_gpio);
}

static void MX_USART2_UART_Init(void) {
    __HAL_RCC_USART2_CLK_ENABLE();

    huart2.Instance = USART2;
    huart2.Init.BaudRate = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK) {
        while (1)
            ;
    }
}

static void MX_I2C1_Init(void) {
    __HAL_RCC_I2C1_CLK_ENABLE();

    hi2c1.Instance = I2C1;
    hi2c1.Init.ClockSpeed = 100000;
    hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1 = 0;
    hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2 = 0;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) {
        while (1)
            ;
    }
}

static void ConsoleTask(void *) {
    for (;;) {
        auto reading = driver_tasks::hts221TaskLatestReading();
        if (reading) {
            printf("temp=%.2f C humidity=%.2f %%RH\r\n", static_cast<double>(reading->temperatureC),
                   static_cast<double>(reading->humidityRH));
        } else {
            printf("hts221: no reading yet\r\n");
        }
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

int main(void) {
    HAL_Init();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();

    printf("\r\nboot: uart console up\r\n");

    if (!driver_tasks::hts221TaskStart(&hi2c1)) {
        printf("boot: hts221 init failed, halting\r\n");
        while (1)
            ;
    }

    xTaskCreate(ConsoleTask, "console", 4 * configMINIMAL_STACK_SIZE, nullptr, tskIDLE_PRIORITY + 1, nullptr);

    vTaskStartScheduler();

    for (;;)
        ;
}
