[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F401RETx"
rustflags = ["-C", "link-arg=-Tlink.x"]

[lib]
name = "firmware"
path = "src/lib.rs"

[[bin]]
name = "firmware"
path = "src/main.rs"

[dev-dependencies]
embedded-hal-mock = "0.11"