[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-rtt-target = "0.1"
rtt-target = "0.5"
stm32f4xx-hal = { version = "0.21", features = ["stm32f401"] }

[profile.release]
debug = true
lto = true
opt-level = "s"

[profile.dev]
debug = true
opt-level = 1
